config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  resources :home, only: [:index]
  resources :locations, only: [:create, :index, :show, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "weather_forecasts#new"
  post "/" => "weather_forecasts#create", as: :weather_forecasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/forecast.rb
class Forecast
  attr_accessor :periods, :location, :data_state, :zipcode, :errors

  delegate :coordinates, :postal_code, :address, to: :location

  def initialize
    @data_state = :cached
    @periods = []
    @errors = []
  end

  def location=(forecast_location)
    @location = forecast_location
    @zipcode = forecast_location&.postal_code.presence || forecast_location&.address&.match(/\d{5}(-\d{4})?/)[0]

    errors << "No location found for this address." if @location.nil?
    errors << "No zipcode found for this address." if @zipcode.nil?
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  geocoded_by :address

  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }

  def coordinates
    [latitude, longitude]
  end

  def forecast
    cache_key = "forecast_#{coordinates.join('_')}"
    Rails.cache.fetch(cache_key, expires_in: 1.hour) do
      WeatherForecastService.new(address).call
    end
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  generates_token_for :email_verification, expires_in: 2.days do
    email
  end
  generates_token_for :password_reset, expires_in: 20.minutes do
    password_salt.last(10)
  end

  has_many :sessions, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 12 }

  normalizes :email, with: -> { _1.strip.downcase }

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end

  has_many :locations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_request_details
  before_action :authenticate

  private
    def authenticate
      if session_record = Session.find_by_id(cookies.signed[:session_token])
        Current.session = session_record
      else
        redirect_to sign_in_path
      end
    end

    def set_current_request_details
      Current.user_agent = request.user_agent
      Current.ip_address = request.ip
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def create
    @location = Current.user.locations.new(location_params)
    if @location.save
      flash.now[:notice] = "Location pinned successfully."
      # redirect_to root_path
      render turbo_stream: [
        turbo_stream.replace(:flash_messages, partial: "shared/flash_messages")
      ]
    else
      render turbo_stream: [
        turbo_stream.replace(:flash_messages, "shared/flashes")
      ]
    end
  end

  def index
    @locations = Current.user.locations
  end

  private

  def location_params
    params.require(:location).permit(:address)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "Your password has been changed"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_user
      @user = Current.user
    end

    def user_params
      params.permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session_record = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true }

      send_email_verification
      redirect_to root_path, notice: "Welcome! You have signed up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.permit(:email, :password, :password_confirmation)
    end

    def send_email_verification
      UserMailer.with(user: @user).email_verification.deliver_later
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: %i[ new create ]

  before_action :set_session, only: :destroy

  def index
    @sessions = Current.user.sessions.order(created_at: :desc)
  end

  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      @session = user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

      redirect_to root_path, notice: "Signed in successfully"
    else
      redirect_to sign_in_path(email_hint: params[:email]), alert: "That email or password is incorrect"
    end
  end

  def destroy
    @session.destroy; redirect_to(sessions_path, notice: "That session has been logged out")
  end

  private
    def set_session
      @session = Current.user.sessions.find(params[:id])
    end
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController

  def new
    @forecast = Forecast.new
  end

  def create
    @forecast = WeatherForecastService.new(weather_forecast_params).call
    if @forecast.periods.present?
      data_state = @forecast.data_state
      flash.now[data_state == :cached ? :warning : :success] = "This data is #{data_state}."
    else
      flash.now[:error] = @forecast.errors
    end

    render :new, status: 301
  end

  private

  def weather_forecast_params
    params.require(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      notice: "alert-success",
      error: "alert-danger"
    }[flash_type.to_sym] || "alert-#{flash_type.to_s}"
  end
end

app/helpers/weather_forecast_helper.rb
module WeatherForecastHelper
  def format_weather_card_time(time_string)
    Time.parse(time_string).strftime("%A %d at %l:%M %p")
  end
end

app/helpers/weather_search_helper.rb
module WeatherSearchHelper
  def format_weather_card_time(time_string)
    Time.parse(time_string).strftime("%A %d at %l:%M %p")
  end

  def format_temperature(temperature)
    temperature.to_f.round(2)
  end

end

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Signed in as <strong><%= Current.user.email %></strong></h2>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h4>Login and verification</h4>
              <%= link_to "Change password", edit_password_path, class: 'btn btn-primary btn-block mb-3' %>
              <%= link_to "Change email address", edit_identity_email_path, class: 'btn btn-primary btn-block mb-3' %>
            </div>
            <div class="col-md-6">
              <h4>Access history</h4>
              <%= link_to "Devices & Sessions", sessions_path, class: 'btn btn-primary btn-block mb-3' %>
            </div>
          </div>
        </div>
        <div class="card-footer text-center">
          <%= button_to "Log out", Current.session, method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_form.html.erb
<%= form_with(url: weather_forecasts_path,
  html: { class: "form-inline ml-auto my-2 my-lg-0" },
  data: { controller: "address", "loading-target": 'form' }) do |form| %>
    <%= form.text_field :address, id: "autocomplete", class: "form-control mr-sm-2", type: "search", placeholder: "Address" %>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- _navbar.html.erb -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary px-lg-5">
  <a class="navbar-brand" href="/">WeatherApp</a>

  <div class="col-12 col-md-6 col-lg-3 ms-auto">
    <%= render 'layouts/form' %>
  </div>

  <div class="ms-auto">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end navbar navbar-expand-lg navbar-dark bg-primary" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
          <% if Current.user %>
            <li class="nav-item">
              <%= link_to 'Profile', home_index_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", Current.session, data: { "turbo-method": :delete }, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", sign_up_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", sign_in_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"  %>
    <%= javascript_importmap_tags %>

    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places"
      async
      defer
    ></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body data-controller="loading">
    <%= render 'layouts/navbar' %>

    <div class="row justify-content-center">
      <%= turbo_frame_tag "flash_messages", style: 'height: 50px' do %>
        <%= render 'shared/flash_messages' %>
      <% end %>
    </div>

    <%= turbo_frame_tag 'pinned_locations', src: locations_path %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_location.html.erb
<% data = location.forecast.periods.first %>

<div class="row justify-content-center text-center">
  <div class="col-sm-4 col-md-3 col-xl-2">
    <div class="card mb-4" style="background-image: url('<%= data['icon'] %>'); background-position: center; background-size: cover; background-repeat: no-repeat;border-radius: 25px;">
      <div class="overlay card-body p-4">
        <div class="d-flex justify-content-between pb-2">
          <div>
            <h2 class="display-2">
              <strong>
                <%= data["temperature"] %> <%= data["temperatureUnit"] %>
              </strong>
            </h2>
            <p class="mb-0"><%= location.address %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<%= turbo_frame_tag :pinned_locations do %>
  <% @locations.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |location| %>
        <%= render location %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div id="<%= key %>" class="alert <%= alert_class_for(key) %>" data-controller="alert">
    <div class="row">
      <div class="col-auto">
        <button type="button" class="btn-close" data-action="alert#close" aria-label="Close"></button>
      </div>
      <div class="col text-center">
        <% if value.is_a?(Array) %>
          <% value.each do |message| %>
            <%= message %><br>
          <% end %>
        <% else %>
          <%= value %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_forecast_card.html.erb
<div class="card mb-4">
  <div class="card-header">
    <h4 class="card-subtitle mb-2 text-muted">
      <%= format_weather_card_time(data["startTime"]) %>
    </h4>
  </div>
  <div class="d-flex justify-content-between mb-4 p-2">
    <div class="col-6">
      <h2 class="display-2"><strong><%= data["temperature"] %> <%= data["temperatureUnit"] %></strong></h2>
      <h4 class="text-muted mb-0"><%= data["name"] %></h4>
    </div>
    <div class="col-4">
      <img src="<%= data["icon"] %>" alt="Weather icon">
    </div>
  </div>
  <div class="card-body">
    <h6 class="card-text"><%= data["shortForecast"] %></h6>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item bg-light">
      <div class="row align-items-center">
        <div class="col-6 font-weight-bold">Start Time:</div>
        <div class="col-6 text-muted"><%= format_weather_card_time(data["startTime"]) %></div>
      </div>
    </li>
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-6">End Time:</div>
        <div class="col-6"><%= format_weather_card_time(data["endTime"]) %></div>
      </div>
    </li>
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-6">Relative Humidity:</div>
        <div class="col-6"><%= data["relativeHumidity"]['value'] %>%</div>
      </div>
    </li>
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-6">Dewpoint:</div>
        <div class="col-6"><%= data["dewpoint"]['value'].to_f.round(2) %>C</div>
      </div>
    </li>

    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-6">Wind Speed:</div>
        <div class="col-6"><%= data["windSpeed"] %></div>
      </div>
    </li>
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-6">Wind Direction:</div>
        <div class="col-6"><%= data["windDirection"] %></div>
      </div>
    </li>
  </ul>
</div>

app/views/weather_forecasts/_forecast.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4"><%= forecast.location&.address %></h1>

  <%= form_with url: locations_path, scope: :location, method: :post, data: { controller: "location" } do |form| %>
    <%= form.hidden_field :address, value: forecast.location&.address %>
    <%= button_tag type: 'submit', class: "pin-button m-1 px-3 py-2 rounded border-0" do %>
      <i class="bi bi-pin"></i>
    <% end %>
  <% end %>

  <% forecast.periods.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |data| %>
        <div class="col-md-4">
          <%= render 'shared/forecast_card', data: data %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/weather_forecasts/new.html.erb
<div data-loading-target="spinner" >
  <%= turbo_frame_tag "weather_forecast" do %>
    <% if @forecast.periods.present? %>
      <%= render partial: 'forecast', locals: { forecast: @forecast } %>
    <% end %>
  <% end %>
</div>